# Generated by Django 6.0.2 on 2026-02-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
                ('eligibility', models.TextField(blank=True)),
                ('official_link', models.URLField(blank=True)),
            ],
        ),
    ]
