# Generated by Django 6.0.2 on 2026-02-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=50)),
                ('soil', models.JSONField()),
                ('duration', models.CharField(max_length=100)),
                ('sowing_time', models.CharField(max_length=100)),
                ('climate', models.TextField()),
                ('rainfall', models.CharField(max_length=100)),
                ('fertilizer', models.CharField(max_length=100)),
                ('irrigation', models.TextField()),
                ('yield_info', models.CharField(max_length=100)),
                ('steps', models.JSONField()),
                ('common_mistakes', models.JSONField()),
                ('images', models.JSONField()),
            ],
        ),
    ]
