# Generated by Django 6.0.2 on 2026-02-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_crop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='images',
        ),
        migrations.AddField(
            model_name='crop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crops/'),
        ),
    ]
