# Generated by Django 5.2.17 on 2026-09-06 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_missing_tables(apps, schema_editor):
    # Older local databases contain these tables without a migration record.
    tables = schema_editor.connection.introspection.table_names()
    for name in ("Feedback", "Doubt"):
        model = apps.get_model("education", name)
        if model._meta.db_table not in tables:
            schema_editor.create_model(model)
        else:
            with schema_editor.connection.cursor() as cursor:
                columns = {
                    column.name for column in schema_editor.connection.introspection.get_table_description(
                        cursor, model._meta.db_table
                    )
                }
            required = {field.column for field in model._meta.local_fields}
            if not required.issubset(columns):
                raise RuntimeError(f"Existing {model._meta.db_table} is missing columns: {required - columns}")


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_remove_crop_images_crop_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    model_operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='doubts/')),
                ('reply', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Answered', 'Answered')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=model_operations),
        # Preserve legacy data on rollback; reapplying validates and adopts the tables.
        migrations.RunPython(create_missing_tables, migrations.RunPython.noop),
    ]
