# Generated by Django 5.2.17 on 2026-09-06 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_remove_crop_images_crop_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crop',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='crop',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='image_license',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='crop',
            name='image_source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='image_status',
            field=models.CharField(choices=[('unverified', '未核验'), ('verified', '已核验'), ('rejected', '不采用')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='crop',
            name='image_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='crop',
            name='source',
            field=models.CharField(default='智农作物知识库', max_length=300),
        ),
        migrations.AddField(
            model_name='crop',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='water',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='applicable_region',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scheme',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='scheme',
            name='deadline',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='scheme',
            name='documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scheme',
            name='how_to_apply',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scheme',
            name='issuing_authority',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scheme',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='source',
            field=models.CharField(default='智农惠农政策库', max_length=300),
        ),
        migrations.AddField(
            model_name='scheme',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='climate',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='common_mistakes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='crop',
            name='duration',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='crop',
            name='fertilizer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='irrigation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='rainfall',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='crop',
            name='season',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='crop',
            name='soil',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='crop',
            name='sowing_time',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='crop',
            name='steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='crop',
            name='yield_info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='doubts/')),
                ('reply', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Answered', 'Answered')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
