# Generated by Django 5.2.17 on 2026-09-08 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['province', 'city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgriProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('pesticide', '农药'), ('fertilizer', '肥料'), ('tool', '器械')], max_length=30)),
                ('active_ingredient', models.CharField(blank=True, max_length=150)),
                ('spec', models.CharField(blank=True, max_length=100)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='件', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_restricted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='farm_app.agristore')),
            ],
            options={
                'ordering': ['store__province', 'store__name', 'price'],
            },
        ),
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('main_crop', models.CharField(choices=[('rice', '水稻'), ('wheat', '小麦'), ('corn', '玉米'), ('soybean', '大豆'), ('vegetable', '蔬菜'), ('fruit', '果树')], max_length=30)),
                ('growth_stage', models.CharField(choices=[('seedling', '苗期'), ('vegetative', '分蘖/拔节期'), ('flowering', '孕穗/抽穗期'), ('grain_filling', '灌浆/成熟期'), ('harvest', '收获期')], default='seedling', max_length=30)),
                ('planting_area', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farm_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PestDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pest_diagnosis/')),
                ('symptom', models.TextField(blank=True)),
                ('diagnosis', models.CharField(max_length=150)),
                ('confidence', models.FloatField(default=0.0)),
                ('severity', models.CharField(choices=[('mild', '轻度'), ('medium', '中度'), ('severe', '重度')], default='mild', max_length=20)),
                ('treatment_plan', models.JSONField(blank=True, default=list)),
                ('needs_human_review', models.BooleanField(default=False)),
                ('review_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', '待确认'), ('pending_review', '转人工复核'), ('treated', '已防治'), ('followed_up', '已回访')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.DateField()),
                ('product_name', models.CharField(max_length=150)),
                ('effect_score', models.PositiveSmallIntegerField()),
                ('loss_avoided', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up', to='farm_app.pestdiagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='FarmTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('pest', '病虫防控'), ('fertilizer', '水肥管理'), ('field', '田间管理'), ('harvest', '收获管理')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('suggested_date', models.DateField()),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='farm_app.farmprofile')),
            ],
            options={
                'ordering': ['suggested_date', '-created_at'],
                'unique_together': {('profile', 'suggested_date', 'title')},
            },
        ),
    ]
